name: panX
channels:
- bioconda
- defaults
- conda-forge
dependencies:
- python=2.7.13
- python-dateutil>=2.5.0
- biopython
- numpy
- scipy
- pandas
- ete2
- diamond
- fasttree
- mafft
- mcl
- raxml
- treetime
