name: panXpy3
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.6
  - python-dateutil>=2.5.0
  - biopython
  - numpy
  - scipy
  - pandas
  - diamond
  - fasttree
  - mafft
  - mcl
  - raxml
  - treetime
  - pip
  - pip:
    - ete3
